disabled suma

diff --git a/bin/chksecurity b/bin/chksecurity
--- a/bin/chksecurity
+++ b/bin/chksecurity
@@ -1,11 +1,11 @@
 #!/bin/bash
-SVER="1.1.9_dev1"
+SVER="1.1.9_dev6"
 ##############################################################################
 # chksecurity - Security Advisory Announcement Checker
 # Copyright (C) 2021 SUSE LLC
 #
 # Description:  Checks and creates SCA patterns for advisories
-# Modified:     2021 Feb 13
+# Modified:     2021 Feb 15
 #
 ##############################################################################
 #
@@ -160,58 +160,97 @@ do
 		(( DUPLICATES++ ))
 	else
 		URL_CONTENT=$(curl --silent ${URL}/${SAIDPG})
-		if echo "$URL_CONTENT" | egrep -i 'suse linux enterprise desktop|suse linux enterprise server|suse linux enterprise module for|suse core 9' &>/dev/null
+		AFFECTED_PRODUCTS=$(sed -e "/Affected Products:/I,/___/p" -n <<< $URL_CONTENT)
+		if egrep -i 'suse manager|client-tools' <<< $AFFECTED_PRODUCTS &>/dev/null
 		then
-			echo "Processing SLE"
-			(( PENDING++ ))
-			sapat.py -q ${URL}/${SAIDPG}
-			RC=$?
-			if (( RC >= 255 )); then
-				(( FAILURES++ ))
-				mv ${CURRENT_PATDIR}/${SAIDPG} ${PAT_ERROR}
-			elif (( RC == 1 )); then
-				(( SKIPPED++ ))
-			elif (( RC > 1 )); then
-				(( UNKNOWN++ ))
-			else
-				(( SUCCESS++ ))
-			fi
-		elif echo "$URL_CONTENT" | egrep -i 'suse manager' &>/dev/null
-		then
-			echo "Processing SUMA+"
+			echo -n "SUMA "
 			(( PENDING++ ))
 			sapat-suma.py -q ${URL}/${SAIDPG}
 			RC=$?
 			if (( $? ))
 			then
+				echo "FAILED"
 				(( FAILURES++ ))
 			else
-				(( SUCCESS++ ))
+				echo "FAILED"
+				(( FAILURES++ ))
+#				echo "Done"
+#				(( SUCCESS++ ))
 			fi
-		elif echo "$URL_CONTENT" | egrep -i 'SUSE Linux Enterprise Real Time Extension' &>/dev/null
+		elif egrep -i 'suse linux enterprise desktop|suse linux enterprise server|suse linux enterprise module for basesystem|suse core 9' <<< ${AFFECTED_PRODUCTS} &>/dev/null
 		then
-			echo "Processing SLE Real Time Kernel"
+			echo -n "SLE "
 			(( PENDING++ ))
 			sapat.py -q ${URL}/${SAIDPG}
 			RC=$?
 			if (( RC >= 255 )); then
+				echo "FAILED"
 				(( FAILURES++ ))
 			elif (( RC == 1 )); then
+				echo "Skipped"
 				(( SKIPPED++ ))
 			elif (( RC > 1 )); then
+				echo "Unknown"
 				(( UNKNOWN++ ))
 			else
+				echo "Done"
 				(( SUCCESS++ ))
 			fi
-		elif echo "$URL_CONTENT" | egrep -i 'suse cloud|suse openstack cloud' &>/dev/null
+		elif egrep -i 'SUSE Linux Enterprise Real Time Extension' <<< $AFFECTED_PRODUCTS  &>/dev/null
 		then
-			echo "Unsupported: SUSE Cloud"
-		elif echo "$URL_CONTENT" | egrep -i 'SUSE Studio' &>/dev/null
+			echo -n "SLE Real Time Kernel "
+			(( PENDING++ ))
+			sapat.py -q ${URL}/${SAIDPG}
+			RC=$?
+			if (( RC >= 255 )); then
+				echo "FAILED"
+				(( FAILURES++ ))
+			elif (( RC == 1 )); then
+				echo "Skipped"
+				(( SKIPPED++ ))
+			elif (( RC > 1 )); then
+				echo "Unknown"
+				(( UNKNOWN++ ))
+			else
+				echo "Done"
+				(( SUCCESS++ ))
+			fi
+		elif egrep -i 'SUSE Linux Enterprise High Availability' <<< ${AFFECTED_PRODUCTS} &>/dev/null
 		then
-			echo "Unsupported: SUSE Studio"
-		elif echo "$URL_CONTENT" | egrep -i 'SUSE Linux Enterprise Server.*-TERADATA' &>/dev/null
+			echo "Unsupported: HAE"
+		elif egrep -i 'SUSE Linux Enterprise High Performance Computing|SUSE Linux Enterprise Module for HPC' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: HPC"
+		elif egrep -i 'SUSE Linux Enterprise Server.*-TERADATA' <<< ${AFFECTED_PRODUCTS} &>/dev/null
 		then
 			echo "Unsupported: Teradata Specific"
+		elif egrep -i 'suse cloud|suse openstack cloud' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: Cloud"
+		elif egrep -i 'SUSE Linux Enterprise Software Development Kit' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: SDK"
+		elif egrep -i 'SUSE Linux Enterprise Live Patching' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: Live Patch"
+		elif egrep -i 'SUSE Studio' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: Studio"
+		elif egrep -i 'SUSE CaaS Platform' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: CaaS"
+		elif egrep -i 'SUSE Enterprise Storage' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: SES"
+		elif egrep -i 'SUSE Linux Enterprise Point of Sale' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: SLEPOS"
+		elif egrep -i 'SUSE Linux Enterprise Workstation Extension' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: WE"
+		elif egrep -i 'SUSE Linux Enterprise Module for' <<< ${AFFECTED_PRODUCTS} &>/dev/null
+		then
+			echo "Unsupported: Module"
 		else
 			echo "Unsupported"
 		fi
