Initial configuration file added

diff --git a/bin/patterns_distribute b/bin/patterns_distribute
--- a/bin/patterns_distribute
+++ b/bin/patterns_distribute
@@ -1,12 +1,12 @@
 #!/bin/bash
-SVER='1.0.0'
+SVER='1.0.1'
 ##############################################################################
 # patterns_distribute - Distribute patterns to their corresponding directories
 # Copyright (C) 2022 SUSE LLC
 #
 # Description:  Moves security patterns to the local github repository linked
 #               to the version of the script.
-# Modified:     2022 Jul 15
+# Modified:     2022 Sep 30
 #
 ##############################################################################
 #
@@ -26,18 +26,9 @@ SVER='1.0.0'
 #     Jason Record <jason.record@suse.com>
 #
 ##############################################################################
-CURRENT_PATDIR="/home/opt/gitwork/"
-PATDIR_BASE='/home/opt/chksecurity'
-PAT_DIR="${PATDIR_BASE}/patterns"
-PAT_ERROR="${PATDIR_BASE}/errors"
-PAT_DUPS="${PATDIR_BASE}/duplicates"
-PAT_LOGS="${PATDIR_BASE}/logs"
 LOG="${PAT_LOGS}/distribute.log"
 CACHE_FILE="${PATDIR_BASE}/_current_pattern_list.txt"
-
-
-BASE_CURRENT='/home/opt/gitwork'
-PAT_DIR='/home/opt/chksecurity/patterns'
+CONF_FILE="/etc/opt/autogen.conf"
 BASE_DIR="$PAT_DIR"
 FORMAT="%s: "
 
@@ -61,13 +52,15 @@ msgn() {
 }
 
 
-SLE10="sle10sp4 sle10sp3 sle10sp2 sle10sp1 sle10sp0"
-SLE11="sle11sp4 sle11sp3 sle11sp2 sle11sp1 sle11sp0"
-SLE12="sle12sp5 sle12sp4 sle12sp3 sle12sp2 sle12sp1 sle12sp0"
-SLE15="sle15sp5 sle15sp4 sle15sp3 sle15sp2 sle15sp1 sle15sp0"
 TOTAL=0
 clear
 title
+if [[ -s $CONF_FILE ]]; then
+	. $CONF_FILE
+else
+	echo "Error: File not found - $CONF_FILE"
+	exit 1
+fi
 BASE_OPT="$1"
 if [[ -n $BASE_OPT ]]; then
 	BASE_DIR=$BASE_OPT
diff --git a/bin/patterns_validate b/bin/patterns_validate
--- a/bin/patterns_validate
+++ b/bin/patterns_validate
@@ -1,12 +1,12 @@
 #!/bin/bash
-SVER='1.0.10'
+SVER='1.0.11'
 ##############################################################################
 # patterns_validate - Validate all new patterns against supportconfigs
 # Copyright (C) 2022 SUSE LLC
 #
 # Description:  Runs new security patterns against supportconfigs in the
 #               archive directory using the pat tool.
-# Modified:     2022 Jul 15
+# Modified:     2022 Sep 30
 #
 ##############################################################################
 #
@@ -28,14 +28,9 @@ SVER='1.0.10'
 ##############################################################################
 
 clear
-CURRENT_PATDIR="/home/opt/gitwork/"
-PATDIR_BASE='/home/opt/chksecurity'
-PAT_DIR="${PATDIR_BASE}/patterns"
-PAT_ERROR="${PATDIR_BASE}/errors"
-PAT_DUPS="${PATDIR_BASE}/duplicates"
-PAT_LOGS="${PATDIR_BASE}/logs"
 LOG="${PAT_LOGS}/validate.log"
 CACHE_FILE="${PATDIR_BASE}/_current_pattern_list.txt"
+CONF_FILE="/etc/opt/autogen.conf"
 CNT=1
 FATALS=0
 DUPLICATES=0
@@ -59,6 +54,12 @@ msgn() {
 	printf "$FORMAT" $1 $2 "$3" | tee -a $LOG
 }
 
+if [[ -s $CONF_FILE ]]; then
+	. $CONF_FILE
+else
+	echo "Error: File not found - $CONF_FILE"
+	exit 1
+fi
 
 if [[ -n $1 ]]; then
 	BASE="$1"
